# Generated by Django 4.2.30 on 2026-06-20 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0002_scan_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='verdict',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
