# Generated by Django 4.2.30 on 2026-06-20 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0004_urlscan'),
    ]

    operations = [
        migrations.AddField(
            model_name='urlscan',
            name='screenshot',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
